# Generated by Django 3.2.7 on 2021-12-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211231_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
